-- Shareable invoice links.
-- A random, unguessable token on the invoice is the only credential. Anonymous
-- visitors never read the invoices table; they call get_shared_invoice(), which
-- returns only the fields needed to render the invoice.

ALTER TABLE public.invoices
  ADD COLUMN IF NOT EXISTS share_token TEXT,
  ADD COLUMN IF NOT EXISTS shared_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS first_viewed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_viewed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS view_count INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS invoices_share_token_unique
  ON public.invoices (share_token) WHERE share_token IS NOT NULL;

-- Owners create or rotate a link through these functions so the token is always
-- generated by the database and cannot be chosen by the client.
CREATE OR REPLACE FUNCTION public.enable_invoice_share(p_invoice_id UUID, p_regenerate BOOLEAN DEFAULT false)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  token TEXT;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication is required' USING ERRCODE = '42501';
  END IF;

  UPDATE public.invoices
  SET share_token = CASE
        WHEN share_token IS NULL OR p_regenerate
        THEN replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '')
        ELSE share_token
      END,
      shared_at = CASE WHEN share_token IS NULL OR p_regenerate THEN now() ELSE shared_at END,
      first_viewed_at = CASE WHEN p_regenerate THEN NULL ELSE first_viewed_at END,
      last_viewed_at = CASE WHEN p_regenerate THEN NULL ELSE last_viewed_at END,
      view_count = CASE WHEN p_regenerate THEN 0 ELSE view_count END
  WHERE id = p_invoice_id AND user_id = auth.uid()
  RETURNING share_token INTO token;

  IF token IS NULL THEN
    RAISE EXCEPTION 'Invoice not found' USING ERRCODE = 'P0002';
  END IF;
  RETURN token;
END;
$$;

CREATE OR REPLACE FUNCTION public.disable_invoice_share(p_invoice_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentication is required' USING ERRCODE = '42501';
  END IF;
  UPDATE public.invoices
  SET share_token = NULL
  WHERE id = p_invoice_id AND user_id = auth.uid();
END;
$$;

-- Public read. Returns NULL for unknown, revoked or archived links.
CREATE OR REPLACE FUNCTION public.get_shared_invoice(p_token TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inv public.invoices%ROWTYPE;
  paid NUMERIC(12,2);
BEGIN
  IF p_token IS NULL OR length(p_token) < 32 THEN
    RETURN NULL;
  END IF;

  SELECT * INTO inv FROM public.invoices
  WHERE share_token = p_token AND archived_at IS NULL;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  -- The owner previewing their own link should not count as a client view.
  IF auth.uid() IS DISTINCT FROM inv.user_id THEN
    UPDATE public.invoices
    SET first_viewed_at = COALESCE(first_viewed_at, now()),
        last_viewed_at = now(),
        view_count = view_count + 1
    WHERE id = inv.id;
  END IF;

  SELECT COALESCE(sum(amount), 0) INTO paid
  FROM public.payment_allocations WHERE invoice_id = inv.id;

  RETURN jsonb_build_object(
    'document_type', inv.document_type,
    'invoice_number', inv.invoice_number,
    'client_name', inv.client_name,
    'client_email', inv.client_email,
    'client_address', inv.client_address,
    'issue_date', inv.issue_date,
    'due_date', inv.due_date,
    'expiry_date', inv.expiry_date,
    'items', inv.items,
    'discount_type', inv.discount_type,
    'discount_value', inv.discount_value,
    'tax_rate', inv.tax_rate,
    'total', inv.total,
    'notes', inv.notes,
    'payment_terms', inv.payment_terms,
    'late_fee_notes', inv.late_fee_notes,
    'footer_text', inv.footer_text,
    'template_id', inv.template_id,
    'currency', inv.currency,
    'status', inv.status,
    'seller_snapshot', inv.seller_snapshot,
    'amount_paid', paid
  );
END;
$$;

REVOKE ALL ON FUNCTION public.get_shared_invoice(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_shared_invoice(TEXT) TO anon, authenticated;
REVOKE ALL ON FUNCTION public.enable_invoice_share(UUID, BOOLEAN) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.enable_invoice_share(UUID, BOOLEAN) TO authenticated;
REVOKE ALL ON FUNCTION public.disable_invoice_share(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.disable_invoice_share(UUID) TO authenticated;

-- Shared invoices show the seller's logo and signature, which live in the
-- private company-assets bucket. Allow anonymous signed-URL creation only for
-- sellers that currently have at least one active share link.
CREATE OR REPLACE FUNCTION public.owner_has_shared_invoice(p_owner TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.invoices
    WHERE user_id::text = p_owner AND share_token IS NOT NULL AND archived_at IS NULL
  );
$$;

REVOKE ALL ON FUNCTION public.owner_has_shared_invoice(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.owner_has_shared_invoice(TEXT) TO anon, authenticated;

DROP POLICY IF EXISTS "Shared invoice assets are viewable" ON storage.objects;
CREATE POLICY "Shared invoice assets are viewable"
ON storage.objects FOR SELECT TO anon
USING (
  bucket_id = 'company-assets'
  AND public.owner_has_shared_invoice((storage.foldername(name))[1])
);
